public class Config {

	/* DO NOT EDIT THIS CLASS! */
	/* This class is generated by Meson for each build. */

	public const string ID = "@NAME@";
	public const string RES_DOMAIN = "@RES_DOMAIN@";
	public const string VERSION = "@VERSION@";

}
